name: RISC-V C程序构建
on:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build-riscv:
    runs-on: ubuntu-22.04
    
    steps:
    - name: checkout code 
      uses: actions/checkout@v4
      
    - name: setup qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: riscv64
        
    - name: setup docker  Buildx
      uses: docker/setup-buildx-action@v3
              
    - name: start container
      run: |
        docker run --platform linux/riscv64 -d --name u24 ubuntu
    
    - name: apt update
      run: |
        docker exec u24 apt-get update
    - name: install neofetch
      run: |
        docker exec u24 apt-get install -y neofetch
        docker exec u24 neofetch
