name: test qemu
on:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build-riscv:
    runs-on: ubuntu-22.04
    
    steps:
    - name: checkout code 
      uses: actions/checkout@v4
      with:
          repository: ffgan/ceph
          ref: feature/allow_riscv64_compile
          submodules: 'true'
      
    - name: setup qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: riscv64
        
    - name: setup docker  Buildx
      uses: docker/setup-buildx-action@v3
              
    - name: start container
      run: |
        docker run --platform linux/riscv64 -d --name u24 -v ./ceph:/src ubuntu bash -c "while true; do sleep 30; done"
        
    - name: ls ceph
      run: |
        docker exec u24 ls -la /src
    - name: apt update
      run: |
        docker exec u24 apt-get update
        docker exec 
    - name: install neofetch
      run: |
        docker exec u24 apt-get install -y neofetch
        docker exec u24 neofetch
    
    - name: post clean
      run: |
        docker stop u24
        docker rm u24
        docker rmi ubuntu
    