name: Build and Run RISC-V Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-riscv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM riscv64/ubuntu:22.04
        
        ENV DEBIAN_FRONTEND=noninteractive
        
        RUN apt-get update && apt-get install -y \
            curl \
            wget \
            vim \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*
        
        RUN echo '#!/bin/bash' > /usr/local/bin/system-info.sh && \
            echo 'echo "=== System Architecture Information ==="' >> /usr/local/bin/system-info.sh && \
            echo 'uname -a' >> /usr/local/bin/system-info.sh && \
            echo 'echo ""' >> /usr/local/bin/system-info.sh && \
            echo 'echo "=== OS Release Information ==="' >> /usr/local/bin/system-info.sh && \
            echo 'cat /etc/os-release' >> /usr/local/bin/system-info.sh && \
            chmod +x /usr/local/bin/system-info.sh
        
        CMD ["/usr/local/bin/system-info.sh"]
        EOF
        
    - name: Build RISC-V Docker image
      run: |
        docker buildx build \
          --platform linux/riscv64 \
          --tag riscv-test:latest \
          --load \
          .
          
    - name: Run RISC-V container and show system info
      run: |
        echo "Running RISC-V container..."
        docker run --rm --platform linux/riscv64 riscv-test:latest
        
    - name: Verify architecture
      run: |
        echo "Verifying the container architecture..."
        docker run --rm --platform linux/riscv64 riscv-test:latest uname -m
        
    - name: Show detailed system information
      run: |
        echo "=== Detailed Container Information ==="
        docker run --rm --platform linux/riscv64 riscv-test:latest bash -c "
          echo 'Architecture: '$(uname -m)
          echo 'Kernel: '$(uname -r)  
          echo 'OS: '$(uname -o)
          echo 'Hostname: '$(uname -n)
          echo ''
          echo '=== CPU Information ==='
          if [ -f /proc/cpuinfo ]; then
            grep -E 'processor|model name|isa' /proc/cpuinfo | head -10
          else
            echo 'CPU info not available'
          fi
          echo ''
          echo '=== Memory Information ==='
          if [ -f /proc/meminfo ]; then
            grep -E 'MemTotal|MemFree' /proc/meminfo
          else
            echo 'Memory info not available'
          fi
        "
        
    - name: Test basic functionality
      run: |
        echo "Testing basic container functionality..."
        docker run --rm --platform linux/riscv64 riscv-test:latest bash -c "
          echo 'Testing basic commands...'
          ls -la /
          echo 'Current user: '$(whoami)
          echo 'Current directory: '$(pwd)
          echo 'Date: '$(date)
        "